// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/check': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/check.post').default>>>>
    }
    '/api/getMonitors': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getMonitors.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/manifest.get').default>>>>
    }
    '/api/verify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/verify.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}